version: '3'

services:
  kafka:
    image: "bitnami/kafka:latest"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER


  producer:
    build: ./producer
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=my-topic  # El nombre del topic al que el producer enviará mensajes
    ports:
      - "3000:3000"
    volumes:
      - ./producer:/app  # Monta el directorio local dentro del contenedor

  consumer:
    build: ./consumer
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=my-topic  # El mismo nombre del topic al que el producer envía mensajes
    volumes:
      - ./consumer:/app  # Monta el directorio local dentro del contenedor
